import { Product, Region } from '@/types';

export const products: Product[] = [
  {
    id: 'fanion-marseille',
    name: 'Fanion Marseille',
    region: 'Marseille',
    price: 22,
    description: 'Inspiré de la cité phocéenne et de ses calanques légendaires. Ce fanion capture l\'essence authentique de Marseille avec ses couleurs méditerranéennes et son esprit maritime rebelle.',
    image: '/images/fanion1.png',
    images: ['/images/fanion1.png'],
    material: 'Tissu premium 100% coton',
    dimensions: '30cm x 20cm',
    category: 'city',
    featured: true,
    inStock: true,
  },
  {
    id: 'fanion-cassis',
    name: 'Fanion Cassis',
    region: 'Cassis',
    price: 22,
    description: 'Cassis, ses falaises blanches et ses eaux turquoise. Un fanion au souffle méditerranéen, chic et marin.',
    image: '/images/fanioncassis.png',
    images: ['/images/fanioncassis.png'],
    material: 'Toile de voile',
    dimensions: '28 × 30 cm',
    category: 'city',
    featured: true,
    inStock: true,
  },
  {
    id: 'fanion-montpellier',
    name: 'Fanion Montpellier',
    region: 'Montpellier',
    price: 22,
    description: 'Montpellier, soleil et élégance du sud. Un fanion lumineux, fait pour les intérieurs comme pour le pont.',
    image: '/images/fanionmontpellier.png',
    images: ['/images/fanionmontpellier.png'],
    material: 'Toile de voile',
    dimensions: '28 × 30 cm',
    category: 'city',
    featured: true,
    inStock: false,
  },
  {
    id: 'fanion-arcachon',
    name: 'Fanion Arcachon',
    region: 'Arcachon',
    price: 22,
    description: 'Arcachon et l’appel du bassin. Un fanion élégant, inspiré des cabanes et des marées.',
    image: '/images/fanionarcachon.png',
    images: ['/images/fanionarcachon.png'],
    material: 'Toile de voile',
    dimensions: '28 × 30 cm',
    category: 'city',
    featured: true,
    inStock: true,
  },
  {
    id: 'fanion-touquet',
    name: 'Fanion Touquet',
    region: 'Le Touquet',
    price: 22,
    description: 'À l’ombre des pins ou au bord de la Canche, ce fanion respire les week-ends chics du Touquet. Entre l’Impasse, l’enduro et les chars à voile, ton bateau a trouvé sa station balnéaire.',
    image: '/images/faniontouquet.png',
    images: ['/images/faniontouquet.png'],
    material: 'Toile de voile',
    dimensions: '28 × 30 cm',
    category: 'city',
    featured: true,
    inStock: true,
  },
];

export const regions: Region[] = [
  {
    id: 'marseille',
    name: 'Marseille',
    description: 'Découvrez notre collection exclusive de fanions Marseille, inspirés de la cité phocéenne et de son patrimoine maritime.',
    image: '/images/region-marseille.jpg',
    products: products.filter(p => p.region === 'Marseille'),
  },
];
